workflows:
  android-apk:
    name: Build Android APK
    environment:
      vars:
        GRADLE_TASK: "assembleDebug" # Gradle task to build APK
      flutter: false # Explicitly set to false for non-Flutter projects
    scripts:
      - echo "Starting the build process..."
      - chmod +x ./gradlew # Make the Gradle wrapper executable
      - ./gradlew $GRADLE_TASK # Run the Gradle task
    artifacts:
      - app/build/outputs/**/*.apk # Location of the APK files
