workflows:
  android-apk:
    name: Build Android APK
    environment:
      vars:
        GRADLE_TASK: "assembleDebug" # Gradle task to build a debug APK
    scripts:
      - echo "Starting the build process..."
      - chmod +x ./gradlew # Make the Gradle wrapper executable
      - ./gradlew $GRADLE_TASK # Execute the Gradle build task
    artifacts:
      - app/build/outputs/**/*.apk # Path to APK artifacts
